# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import pyacs
release = pyacs.__version__          # full version, e.g. "0.66.18"
version = release
project = f'PYACS {release}'         # sidebar title: "PYACS 0.66.18"
copyright = '2026, Jean-Mathieu NOCQUET'
author = 'Jean-Mathieu NOCQUET'
from datetime import datetime
today = datetime.now().strftime("%Y-%m-%d")

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",     # if you use NumPy/Google style docstrings
    "sphinx.ext.viewcode",
    "sphinx.ext.autosummary",  # optional but very useful
    "sphinx.ext.githubpages", # to generate github pages
]

# Stubs are pre-generated by docs/tools/generate_autosummary_stubs.py; do not overwrite them
autosummary_generate = False

templates_path = ['_templates']
# Add our snippet to the sidebar for all pages
html_sidebars = {
    "**": [
        "globaltoc.html",
        "relations.html",
        "sidebar-version.html",  # <-- our file
        "searchbox.html",
    ]
}
exclude_patterns = []



# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'
html_context = {
    "display_version": True,
}
html_static_path = ['_static']
