# ###############################################################################
# # CUSTOM IMPORT
# ###############################################################################
#
# __custom_import__ = [
# # FILTERS
# 'filters.savitzky_golay' ,
# 'filters.wiener' ,
# 'filters.spline' ,
# 'filters.total_variation' ,
# 'filters.piecewise_linear' ,
# 'filters.el1_trend' ,
# 'filters.minimum_component' ,
# 'filters.l1_trend' ,
# 'filters.median' ,
# 'filters.smooth' ,
# 'filters.vondrak' ,
# # PLOT
# 'plot.gts_to_ts' ,
# 'plot.plot_ts' ,
# 'plot.plot' ,
# 'plot.init_plot_settings' ,
# 'plot.make_stitle' ,
# 'plot.init_plot_default' ,
# # NON LINEAR MODEL
# 'non_linear_model.non_linear_gts_model' ,
# # PRIMITIVE
# 'primitive.extract_dates' ,
# 'primitive.extract_ndates_before_date' ,
# 'primitive.cdata' ,
# 'primitive.correct_duplicated_dates' ,
# 'primitive.insert_gts_data' ,
# 'primitive.decimate' ,
# 'primitive.extract_ndates_after_date' ,
# 'primitive.add_obs_xyz' ,
# 'primitive.substract_ts_daily' ,
# 'primitive.extract_periods' ,
# 'primitive.copy' ,
# 'primitive.find_large_uncertainty' ,
# 'primitive.exclude_periods' ,
# 'primitive.substract_ts' ,
# 'primitive.remove_velocity' ,
# 'primitive.set_zero_at_date' ,
# 'primitive.xyz2neu' ,
# 'primitive.get_coseismic' ,
# 'primitive.reorder' ,
# 'primitive.interpolate' ,
# 'primitive.differentiate' ,
# 'primitive.extract_ndates_around_date' ,
# 'primitive.neu2xyz' ,
# 'primitive.add_offsets_dates' ,
# 'primitive.add_obs' ,
# 'primitive.rotate' ,
# 'primitive.split_gap' ,
# 'primitive.displacement' ,
# # MODEL
# 'model.detrend_seasonal' ,
# 'model.detrend_annual' ,
# 'model.detrend' ,
# 'model.remove_pole' ,
# 'model.make_model' ,
# 'model.mmodel' ,
# 'model.detrend_seasonal_median' ,
# 'model.frame' ,
# 'model.detrend_median' ,
# 'model.add_vel_sigma' ,
# # FORMAT
# 'format.pos' ,
# 'format.mb_file' ,
# 'format.track' ,
# 'format.kenv' ,
# 'format.to_pandas_df' ,
# 'format.tdp' ,
# 'format.force_daily' ,
# 'format.get_unr' ,
# 'format.cats' ,
# 'format.pride' ,
# # MODULES
# # 'message' ,
# # 'trajectory' ,
# # 'offset' ,
# # 'outliers_old' ,
# # 'step_detect_edge_filter' ,
# # 'outliers.find_l1trend' ,
# # 'outliers.find_outliers_simple' ,
# # 'outliers.find_outliers_around_date' ,
# # 'outliers.find_outliers_percentage' ,
# # 'outliers.find_outliers_vondrak' ,
# # 'outliers.find_outliers_sliding_window' ,
# # 'outliers.remove_outliers' ,
# # 'noise' ,
# # 'gts_estimators' ,
# # 'metadata' ,
# # 'gts_dates' ,
# # 'model_old' ,
# # 'errors' ,
# # 'tensor_ts.sgts2tsr' ,
# # 'plotold' ,
# # 'step_detect' ,
# ]
#
# for mod in __custom_import__:
#     exec('from .' + mod + ' import *')
